### ISSUE TITLE
Dropdown label not displayed correctly

### ISSUE THREAD

**Issue by akmalelias** [tightenco/nova-google-analytics#11]
Nova: v2.0.3
nova-google-analytics: v0.1.6

Hi, I have updated my nova-google-analytics to the latest version 0.1.6. After update it, the dropdown label no longer appear. Below is the screenshot for your reference. Any thoughts? thanks

![image](https://user-images.githubusercontent.com/20658464/57092196-6c5d5780-6d3d-11e9-9caf-c2d220ab4d09.png)

**Comment by mattstauffer** [comment]
@akmalelias Is this no longer a problem?

**Comment by akmalelias** [comment]
@mattstauffer i have tried downgrade Nova to version 2.0.2 and it can display the label correctly. So i guess nothing to do with this package. Might need to crosscheck the Nova changes between 2.0.2 & 2.0.3.

**Comment by mattstauffer** [comment]
@akmalelias Ahh, thanks! I'll try to take a look later.
