### ISSUE TITLE
Does the Referrers List card work?

### ISSUE THREAD

**Issue by dmyers** [tightenco/nova-google-analytics#17]
I noticed that the class the card extends had the wrong casing and made PR #16 for it.

I then still had an issue I haven't yet solved with the card being blank when I have referrals in Google Analytics so I don't think it's the data source.

In my cards array:
```php
use Tightenco\NovaGoogleAnalytics\PageViewsMetric as AnalyticsPageViews;
use Tightenco\NovaGoogleAnalytics\VisitorsMetric as AnalyticsVisitors;
use Tightenco\NovaGoogleAnalytics\MostVisitedPagesCard as AnalyticsTopPages;
use Tightenco\NovaGoogleAnalytics\ReferrersList as AnalyticsTopReferrers;

    protected function cards()
    {
        return [
            new AnalyticsPageViews,
            new AnalyticsVisitors,
            new AnalyticsTopPages,
            new AnalyticsTopReferrers,
            new ProductClicks,
        ];
    }
```

<img width="1076" alt="" src="https://user-images.githubusercontent.com/207171/80390221-c2da7480-8871-11ea-9ab4-568ed96146b7.png">

**Comment by mattstauffer** [comment]
Hm. Let me take a look at whether I wrote that or whether someone else wrote it.

**Comment by mattstauffer** [comment]
https://github.com/tightenco/nova-google-analytics/pull/10

Yah, this is a PR, so I was only relying on the PR author saying it worked for her. Any thoughts on what's wrong? I don't even have a great GA account to test it on right now.
