### ISSUE TITLE
How to add translation to cards?

### ISSUE THREAD

**Issue by pieinn** [tightenco/nova-google-analytics#38]
Please advice how to translate following cards: 
Page View
Most Visited Pages
Visitors
Top Referrers

Thanks

**Comment by krievley** [comment]
@laraketai - There is some good documentation on the Nova website for adding translation files to your Nova instance. https://nova.laravel.com/docs/3.0/customization/localization.html

To create a new translation you use the following `artisan` command: `php artisan nova:translate [language]`
Nova translations are stored in `resources/lang/vendor/nova`
The translation file is a JSON format so you would type something like:
```
"Page View": "Translation"
"Most Visited Pages": "Translation"
"Visitors": "Translation"
"Top Referrers": "Translation"
```
