### ISSUE TITLE
SessionsByDeviceMetric and SessionsByCountryMetric not found

### ISSUE THREAD

**Issue by pieinn** [tightenco/nova-google-analytics#39]
Class "Tightenco\NovaGoogleAnalytics\SessionsByDeviceMetric" not found
Class "Tightenco\NovaGoogleAnalytics\SessionsByCountryMetric" not found

**Comment by mattstauffer** [comment]
Thanks for the comment--we hadn't pushed out a release with those features yet, but they're now tagged in `v0.2.1`.

https://github.com/tighten/nova-google-analytics/releases/tag/v0.2.1
