### ISSUE TITLE
Getting a 500 error on an asset

### ISSUE THREAD

**Issue by thatleeguy** [tightenco/nova-google-analytics#4]
<img width="953" alt="screenshot 2018-09-01 20 20 25" src="https://user-images.githubusercontent.com/93346/44951550-919f6c00-ae24-11e8-8934-77b2e3013c01.png">

Let me know if/how I can help you get to the bottom of this.

**Comment by mattstauffer** [comment]
90% sure it’s just because I never wrote a style but I used a skeleton that tells nova to look for it. I think I can comment out a single line of code and be good.

**Comment by mattstauffer** [comment]
@thatleeguy Pushing a release now that should fix this.
