### ISSUE TITLE
how can use card in blade template kindly any reference link

### ISSUE THREAD

**Issue by zainawan99** [tightenco/nova-google-analytics#47]

**Comment by krievley** [comment]
As of now, I believe that any Cards created with Nova can only be used inside of Nova itself. The documentation for the Card [assets](https://nova.laravel.com/docs/3.0/customization/cards.html#assets), should point you to the location of the `Vue` files that are created for a Nova Card. You should be able to import these `Vue` files into any page inside of Nova. Furthermore, Nova has the ability to define custom [Dashboards](https://nova.laravel.com/docs/3.0/customization/dashboards.html) that will also load Cards. Please let me know if this was helpful, or if you have a followup question.
