### ISSUE TITLE
Not working with GA 4

### ISSUE THREAD

**Issue by jastranlove2020** [tightenco/nova-google-analytics#54]
dev does not try this package, it is not working with GA 4 now

it took many hours to fix problem but not success 

"{
  "error": {
    "code": 403,
    "message": "User does not have sufficient permissions for this profile.",
    "errors": [
      {
        "message": "User does not have sufficient permissions for this profile.",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ]
  }
}
"
after review Issues, then i confirm that Ga4 is not supported now March 2024.

the author, please mark project abandoned so that does not take other dev's time

thank you

**Comment by forgecodex** [comment]
I have been researching for a long time and encountered the same problem.

**Comment by driftingly** [comment]
@beiaduo Please try V4: https://github.com/tighten/nova-google-analytics/releases/tag/v4.0.0
