### ISSUE TITLE
Range selection

### ISSUE THREAD

**Issue by mischasigtermans** [tightenco/nova-google-analytics#9]
Hi! When are you finishing the range selection? Would nice to see more cards. Cheers.

**Comment by mattstauffer** [comment]
Thank you for the reminder! I did a terrible thing by starting this and leaving it hanging. It’s third on my todo list right now so hopefully I will very soon!!

**Comment by mattstauffer** [comment]
@Pixelstart adding range selection to page views and visitors now. Are there other cards you'd find useful?
